# Site settings
title: Luckych454.github.io
description: > # this means to ignore newlines until "baseurl:"
  A tiny site of Luckych's.<br />
  Powered by Jekyll + GitHub Pages.

exclude: ['about.md', 'categories.md']
plugins: [jekyll-paginate]

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://Luckych454.github.io" # the base hostname & protocol for your site

github_username:  Luckych454

githubio_https_redirect: true
google_analytics: UA-54761187-1

paginate: 10 # pagination based on number of posts

defaults:
  - scope:
      type: posts
    values:
      layout: post
      author: Luckych

# Build settings
markdown: kramdown
