# Site settings
title: Luckych454
#email: 851022445a@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Vanilla site with vanilla theme.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://Luckych454.github.io" # the base hostname & protocol for your site

#twitter_username: jekyllrb
github_username:  Luckych454

githubio_https_redirect: true
google_analytics: vanilla

paginate: 10 # pagination based on number of posts

defaults:
  - scope:
      type: posts
    values:
      layout: post
      author: Chris

# Build settings
markdown: kramdown
